/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import Connectors.dbconnect;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CustomerCheckin extends javax.swing.JFrame {
     private Connection conn;
     private String query;
    private String updateCustomerQuery;
    /**
     * Creates new form CustomerCheckin
     */
    public CustomerCheckin() {
        initComponents();
        dbconnect dbc = new dbconnect();
        conn = dbc.getConnection();
        loadData();
        
    }
    public void loadData(){
        //CustomerCheckin();
        JFrame frame = new JFrame("Data from Database");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //String[] columnNames = {"Tenant ID", "First Name", "Last Name", "Gender", "Bed", "No of Pax", "Contact Number", "Room ID", "Check In Date", "Check Out Date", "Room Type"};
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        //model.addRow(columnNames);
        JTable table = new JTable(model);
        model.setRowCount(0);

    try {
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM customertenants";
            ResultSet rs = stmt.executeQuery(query);
 
            while (rs.next()) {
                int tenantID = rs.getInt("TenantID");
                String tenantName = rs.getString("TenantName");
                String tenantLName = rs.getString("LastName");
                String gender = rs.getString("Gender");
                String bed = rs.getString("Bed");
                int np = rs.getInt("NoofPax");
                String contact = rs.getString("ContactNumber");
                int roomID = rs.getInt("RoomID");
                String cid = rs.getString("CheckInDate");
                String cod = rs.getString("CheckOutDate");
                String rType = rs.getString("RoomType");
                Object[] rowData = {tenantID, tenantName, tenantLName, gender, bed, np, contact, roomID, cid, cod, rType};
                model.addRow(rowData);
            }
 
            rs.close();
            stmt.close();
            //conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        jScrollPane1.add(table);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bttnexit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelFName = new javax.swing.JLabel();
        labelRId = new javax.swing.JLabel();
        txtTenantName = new javax.swing.JTextField();
        txtRoomID = new javax.swing.JTextField();
        txtcheckin = new javax.swing.JTextField();
        bttnClear = new javax.swing.JButton();
        lblContact = new javax.swing.JLabel();
        txtContactNum = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblCheckin = new javax.swing.JLabel();
        lblCheckout = new javax.swing.JLabel();
        txtcheckout = new javax.swing.JTextField();
        bCheckin = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        labelTId = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        txtTenantID = new javax.swing.JTextField();
        bttnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblGender = new javax.swing.JLabel();
        CboxGender = new javax.swing.JComboBox<>();
        lblGender1 = new javax.swing.JLabel();
        Cboxtype = new javax.swing.JComboBox<>();
        lblGender2 = new javax.swing.JLabel();
        CbRoomtype = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttnSearch = new javax.swing.JButton();
        lblNoPax = new javax.swing.JLabel();
        CboxNoOfPax = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-in-desk.png"))); // NOI18N
        jLabel4.setText("Customer Maintenance");

        bttnexit.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        bttnexit.setText("Back");
        bttnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnexitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        labelFName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelFName.setText("First Name:");
        labelFName.setToolTipText("");

        labelRId.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelRId.setText("Room ID:");
        labelRId.setToolTipText("");

        txtTenantName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtTenantName.setToolTipText("");

        txtRoomID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtRoomID.setToolTipText("");
        txtRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomIDActionPerformed(evt);
            }
        });

        txtcheckin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtcheckin.setToolTipText("");
        txtcheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckinActionPerformed(evt);
            }
        });

        bttnClear.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        bttnClear.setText("Clear");
        bttnClear.setToolTipText("");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });

        lblContact.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblContact.setText("Contact #:");
        lblContact.setToolTipText("");

        txtContactNum.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtContactNum.setToolTipText("");

        lblLName.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblLName.setText("Last Name:");
        lblLName.setToolTipText("");

        lblCheckin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblCheckin.setText("Check In Date:");
        lblCheckin.setToolTipText("");

        lblCheckout.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblCheckout.setText("Check Out Date:");
        lblCheckout.setToolTipText("");

        txtcheckout.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtcheckout.setToolTipText("");

        bCheckin.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        bCheckin.setText("Check in");
        bCheckin.setToolTipText("");
        bCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckinActionPerformed(evt);
            }
        });

        bDel.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        bDel.setText("Delete");
        bDel.setToolTipText("");
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });

        labelTId.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        labelTId.setText("Tenant ID:");
        labelTId.setToolTipText("");

        txtLname.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtLname.setToolTipText("");

        txtTenantID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txtTenantID.setToolTipText("");
        txtTenantID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenantIDActionPerformed(evt);
            }
        });

        bttnUpdate.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        bttnUpdate.setText("Update");
        bttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tenant ID", "First Name", "Last Name", "Gender", "Bed", "No of Pax", "Contact Num.", "Room ID", "Check In Date", "Check Out Date", "Room Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lblGender.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblGender.setText("Gender:");
        lblGender.setToolTipText("");

        CboxGender.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female ", "Male", "Unknown" }));

        lblGender1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblGender1.setText("Bed:");
        lblGender1.setToolTipText("");

        Cboxtype.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        Cboxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Barkada", "Family Size" }));

        lblGender2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblGender2.setText("Room Type:");
        lblGender2.setToolTipText("");

        CbRoomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        bttnSearch.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        bttnSearch.setText("Search Tenant ID");
        bttnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSearchActionPerformed(evt);
            }
        });

        lblNoPax.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        lblNoPax.setText("No of Pax:");

        CboxNoOfPax.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CboxNoOfPax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "5", "8" }));

        jButton1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jButton1.setText("Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFName)
                                    .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNoPax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLname, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(txtTenantName, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(CboxGender, 0, 168, Short.MAX_VALUE)
                                    .addComponent(Cboxtype, 0, 168, Short.MAX_VALUE)
                                    .addComponent(CboxNoOfPax, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelTId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenantID, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelRId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(CbRoomtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCheckout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bCheckin)
                                    .addComponent(bDel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTId)
                            .addComponent(txtTenantID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContact)
                            .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLName)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckout)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCheckin)
                            .addComponent(bttnClear))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bDel)
                            .addComponent(bttnUpdate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(CboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender2)
                            .addComponent(CbRoomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender1)
                            .addComponent(Cboxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNoPax)
                            .addComponent(CboxNoOfPax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bttnSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnexit)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bttnexit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnexitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bttnexitActionPerformed

    private void txtRoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomIDActionPerformed

    private void txtcheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckinActionPerformed

    }//GEN-LAST:event_txtcheckinActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        setVisible(false);
        new CustomerCheckin().setVisible(true);
    }//GEN-LAST:event_bttnClearActionPerformed

    private void bCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckinActionPerformed
                              
    String sTid = txtTenantID.getText();
    String sTname = txtTenantName.getText();
    String sLname = txtLname.getText();
    String sContact = txtContactNum.getText();
    String sRID = txtRoomID.getText();
    String sCID = txtcheckin.getText();
    String sCOD = txtcheckout.getText();
    String sGender = (String) CboxGender.getSelectedItem();
    String sBed = (String) Cboxtype.getSelectedItem();
    String sNoOfPax = (String) CboxNoOfPax.getSelectedItem();
    String sRoomType = (String) CbRoomtype.getSelectedItem();

    try {
        int RoomID = Integer.parseInt(sRID);
        int i = 1;

        try (Connection connect = dbconnect.getConnection()) {
            // Check if room is available
            String checkRoomQuery = "SELECT Status FROM rooms WHERE RoomID = ?";
            PreparedStatement checkRoomStmt = connect.prepareStatement(checkRoomQuery);
            checkRoomStmt.setInt(1, RoomID);
            ResultSet rs = checkRoomStmt.executeQuery();

            if (rs.next()) {
                String roomStatus = rs.getString("Status");
                if (!roomStatus.equals("Available")) {
                    JOptionPane.showMessageDialog(null, "Room is not available!", "Room Error", JOptionPane.ERROR_MESSAGE);
                    return; // Exit if the room is not available
                }
            } else {
                JOptionPane.showMessageDialog(null, "Room ID does not exist!", "Room Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit if the room does not exist
            }

            // Insert the tenant data into the database
            String query = "INSERT INTO `customertenants` (`TenantID`, `TenantName`, `LastName`, `Gender`, `Bed`, `NoofPax`, `ContactNumber`, `RoomID`, `CheckInDate`, `CheckOutDate`, `RoomType`) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = connect.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            pstmt.setString(i, sTid);
            pstmt.setString(i++, sTname);
            pstmt.setString(i++, sLname);
            pstmt.setString(i++, sGender);
            pstmt.setString(i++, sBed);
            pstmt.setString(i++, sNoOfPax);
            pstmt.setString(i++, sContact);
            pstmt.setInt(i++, RoomID);
            pstmt.setString(i++, sCID);
            pstmt.setString(i++, sCOD);
            pstmt.setString(i++, sRoomType);
            pstmt.executeUpdate();

            // Update room status to 'Occupied'
            String updateRoomQuery = "UPDATE rooms SET Status = ? WHERE RoomID = ?";
            PreparedStatement updateRoomStmt = connect.prepareStatement(updateRoomQuery);
            updateRoomStmt.setString(1, "Occupied");
            updateRoomStmt.setInt(2, RoomID);
            updateRoomStmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "New Tenant Added!", "Adding Tenant Successfully", JOptionPane.INFORMATION_MESSAGE);

            // Clear the input fields
            txtTenantName.setText("");
            txtLname.setText("");
            CboxGender.setSelectedItem("Male");
            Cboxtype.setSelectedItem("Single");
            CboxNoOfPax.setSelectedItem("1");
            txtContactNum.setText("");
            txtRoomID.setText("");
            txtcheckin.setText("");
            txtcheckout.setText("");
            CbRoomtype.setSelectedItem("AC");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Adding Unsuccessfully!", "TenantError!", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Room ID must be a number!", "Input Error", JOptionPane.ERROR_MESSAGE);
    }


    

   
    }//GEN-LAST:event_bCheckinActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        String sTID = txtTenantID.getText();
        String sRID = txtRoomID.getText();
        /*String sTname = txtTenantName.getText();
        String sLname = txtLname.getText();
        String sContact = txtContactNum.getText();
        String sRID = txtRoomID.getText();
        String sCID = txtcheckin.getText();
        String sCOD = txtcheckout.getText();

        int ID = Integer.parseInt(sTID);
        int RoomID = Integer.parseInt(sRID);*/

        try {
            /*Statement stmt= conn.createStatement();
            String query = "DELETE FROM `customertenants` WHERE `customertenants`.`TenantID` = '"+sTID+"'";
            stmt.execute(query);*/
            Connection connect = dbconnect.getConnection();
            String query = "DELETE FROM `customertenants` WHERE `TenantID` = ?";
            PreparedStatement deleteRoomStmt = connect.prepareStatement(query);
            deleteRoomStmt.setInt(1, Integer.parseInt(sTID));
            deleteRoomStmt.executeUpdate();
            loadData();
            
            int RoomID = Integer.parseInt(sRID);
            String updateRoomQuery = "UPDATE rooms SET Status = ? WHERE RoomID = ?";
            PreparedStatement updateRoomStmt = connect.prepareStatement(updateRoomQuery);
            updateRoomStmt.setString(1, "Available");
            updateRoomStmt.setInt(2, RoomID);
            updateRoomStmt.executeUpdate();
            
            
            JOptionPane.showMessageDialog(null, "Tenant Deleted!", "Deleting Tenant Successfully", 0);

        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Deleting Unsuccessfully!", "TenantError!", 0);
            e.printStackTrace();
        } 
    }//GEN-LAST:event_bDelActionPerformed

    private void txtTenantIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenantIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenantIDActionPerformed

    private void bttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateActionPerformed

    // Get the TenantID from the text field
    String tenantID = txtTenantID.getText();

    // Validate TenantID
    if (tenantID == null || tenantID.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please search for a tenant before updating!", "Update Error", JOptionPane.WARNING_MESSAGE);
        return; // Exit if TenantID is not valid
    }

    // Retrieve updated values from the text fields
    String sTname = txtTenantName.getText();
    String sLname = txtLname.getText();
    String sContact = txtContactNum.getText();
    String sRID = txtRoomID.getText();
    String sCID = txtcheckin.getText();
    String sCOD = txtcheckout.getText();
    String sGender = (String) CboxGender.getSelectedItem();
    String sBed = (String) Cboxtype.getSelectedItem();
    String sNoOfPax = (String) CboxNoOfPax.getSelectedItem();
    String sRoomType = (String) CbRoomtype.getSelectedItem();

    try (Connection connect = dbconnect.getConnection()) {
        // Update query to modify tenant data
        String query = "UPDATE customertenants SET TenantName = ?, LastName = ?, Gender = ?, Bed = ?, NoofPax = ?, ContactNumber = ?, RoomID = ?, CheckInDate = ?, CheckOutDate = ?, RoomType = ? WHERE TenantID = ?";
        PreparedStatement pstmt = connect.prepareStatement(query);

        // Bind the updated values to the query
        pstmt.setString(1, sTname);
        pstmt.setString(2, sLname);
        pstmt.setString(3, sGender);
        pstmt.setString(4, sBed);
        pstmt.setString(5, sNoOfPax);
        pstmt.setString(6, sContact);
        pstmt.setString(7, sRID);
        pstmt.setString(8, sCID);
        pstmt.setString(9, sCOD);
        pstmt.setString(10, sRoomType);
        pstmt.setString(11, tenantID);

        // Execute the update query
        int rowsUpdated = pstmt.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Tenant details updated successfully!", "Update Success", JOptionPane.INFORMATION_MESSAGE);
            loadData(); // Reload data if displayed in a table or list
        } else {
            JOptionPane.showMessageDialog(null, "No tenant found with the given Tenant ID.", "Update Failed", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error updating tenant details!", "Database Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

  
    }//GEN-LAST:event_bttnUpdateActionPerformed

    private void bttnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSearchActionPerformed
                                           
    String tenantID = txtTenantID.getText(); // Retrieve TenantID from the text field

    if (tenantID == null || tenantID.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a valid Tenant ID!", "Input Error", JOptionPane.WARNING_MESSAGE);
        return; // Exit the method if no TenantID is provided
    }

    try (Connection connect = dbconnect.getConnection()) {
        // Query to search for tenant details by TenantID
        String query = "SELECT * FROM customertenants WHERE TenantID = ?";
        PreparedStatement pstmt = connect.prepareStatement(query);
        pstmt.setString(1, tenantID);

        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            // Populate the text fields with tenant details
            txtTenantID.setText(rs.getString("TenantID"));
            txtTenantName.setText(rs.getString("TenantName"));
            txtLname.setText(rs.getString("LastName"));
            txtContactNum.setText(rs.getString("ContactNumber"));
            txtRoomID.setText(rs.getString("RoomID"));
            txtcheckin.setText(rs.getString("CheckInDate"));
            txtcheckout.setText(rs.getString("CheckOutDate"));
            CboxGender.setSelectedItem(rs.getString("Gender"));
            Cboxtype.setSelectedItem(rs.getString("Bed"));
            CboxNoOfPax.setSelectedItem(rs.getString("NoofPax"));
            CbRoomtype.setSelectedItem(rs.getString("RoomType"));

            JOptionPane.showMessageDialog(null, "Tenant Found!", "Search Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Show message if no tenant is found
            JOptionPane.showMessageDialog(null, "No tenant found with the given Tenant ID.", "Search Failed", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error searching for tenant!", "Database Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_bttnSearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.rowAtPoint(evt.getPoint());
        txtTenantID.setText(Integer.toString( (int)jTable1.getValueAt(row, 0)));
        txtTenantName.setText((String)jTable1.getValueAt(row, 1));
        txtLname.setText((String)jTable1.getValueAt(row, 2));
        CboxGender.setSelectedItem((String)jTable1.getValueAt(row, 3));
        Cboxtype.setSelectedItem((String)jTable1.getValueAt(row, 4));
        CboxNoOfPax.setSelectedItem(Integer.toString( (int)jTable1.getValueAt(row, 5)));
        txtContactNum.setText((String) jTable1.getValueAt(row, 6));
        txtRoomID.setText(Integer.toString( (int)jTable1.getValueAt(row, 7)));
        txtcheckin.setText((String) jTable1.getValueAt(row, 8));
        txtcheckout.setText((String) jTable1.getValueAt(row, 9));
        CbRoomtype.setSelectedItem((String)jTable1.getValueAt(row, 10));
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new PaymentMethod().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbRoomtype;
    private javax.swing.JComboBox<String> CboxGender;
    private javax.swing.JComboBox<String> CboxNoOfPax;
    private javax.swing.JComboBox<String> Cboxtype;
    private javax.swing.JButton bCheckin;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnSearch;
    private javax.swing.JButton bttnUpdate;
    private javax.swing.JButton bttnexit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelFName;
    private javax.swing.JLabel labelRId;
    private javax.swing.JLabel labelTId;
    private javax.swing.JLabel lblCheckin;
    private javax.swing.JLabel lblCheckout;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblGender2;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblNoPax;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtTenantID;
    private javax.swing.JTextField txtTenantName;
    private javax.swing.JTextField txtcheckin;
    private javax.swing.JTextField txtcheckout;
    // End of variables declaration//GEN-END:variables
}
