package GUI;

import Connectors.dbconnect;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class View_Available_Apartments extends javax.swing.JFrame {
        private Connection conn;
        private String query;
    /**
     * Creates new form View_Available_Apartments
     */
    public View_Available_Apartments() {
        initComponents();
        dbconnect dbc = new dbconnect();
        conn = dbc.getConnection();
        loadData();
    }
    
    public void loadData(){
        JFrame frame = new JFrame("Data from Database");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        JTable table = new JTable(model);
        model.setRowCount(0);
        
    try{
        Statement stmt = conn.createStatement();
        String query = "SELECT * FROM rooms WHERE Status = 'Available'";
        ResultSet rs = stmt.executeQuery(query);
        
        while(rs.next()){
            int roomID = rs.getInt("RoomID");
            String bedType = rs.getString("BedType");
            int roomSize = rs.getInt("RoomSize");
            int noofOccupants = rs.getInt("NoofAvailableBed");
            double roomPrice = rs.getDouble("RoomPricePerHead");
            String roomStatus = rs.getString("Status");
            
            Object[] rowData = {roomID, bedType, roomSize, noofOccupants, roomPrice, roomStatus};
            model.addRow(rowData);
        }
            rs.close();
            stmt.close();
        } catch (SQLException e){
            e.printStackTrace();
        }
        jScrollPane1.add(table);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnexit = new javax.swing.JButton();
        bttnAddRooms = new javax.swing.JButton();
        bttnDeleteRooms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hallway (1).png"))); // NOI18N
        jLabel1.setText("Available All Apartments");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Bed Type", "Room Size", "No Of Occupants", "Room Price Per Head", "Status "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(2000, 1000));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bttnexit.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        bttnexit.setText("BACK");
        bttnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnexitActionPerformed(evt);
            }
        });

        bttnAddRooms.setText("Add Rooms");
        bttnAddRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddRoomsActionPerformed(evt);
            }
        });

        bttnDeleteRooms.setText("Delete Rooms");
        bttnDeleteRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeleteRoomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(bttnAddRooms)
                        .addGap(29, 29, 29)
                        .addComponent(bttnDeleteRooms)
                        .addGap(346, 346, 346)
                        .addComponent(bttnexit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttnexit)
                        .addComponent(bttnAddRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnDeleteRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnexitActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bttnexitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void bttnAddRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddRoomsActionPerformed
        
    javax.swing.JTextField roomIDField = new javax.swing.JTextField();
    javax.swing.JTextField bedTypeField = new javax.swing.JTextField();
    javax.swing.JTextField roomSizeField = new javax.swing.JTextField();
    javax.swing.JTextField noOfOccupantsField = new javax.swing.JTextField();
    javax.swing.JTextField roomPriceField = new javax.swing.JTextField();
    javax.swing.JTextField statusField = new javax.swing.JTextField();

    Object[] inputFields = {
        "Room ID (Integer):", roomIDField,
        "Bed Type (String):", bedTypeField,
        "Room Size (Integer):", roomSizeField,
        "Number of Occupants (Integer):", noOfOccupantsField,
        "Room Price Per Head (Double):", roomPriceField,
        "Status (String):", statusField
    };

    int option = javax.swing.JOptionPane.showConfirmDialog(null, inputFields, "Add New Room", javax.swing.JOptionPane.OK_CANCEL_OPTION);
    if (option == javax.swing.JOptionPane.OK_OPTION) {
        try {
            
            int roomID = Integer.parseInt(roomIDField.getText().trim());
            String bedType = bedTypeField.getText().trim();
            int roomSize = Integer.parseInt(roomSizeField.getText().trim());
            int noOfOccupants = Integer.parseInt(noOfOccupantsField.getText().trim());
            double roomPrice = Double.parseDouble(roomPriceField.getText().trim());
            String status = statusField.getText().trim();

            
            String insertQuery = "INSERT INTO rooms (RoomID, BedType, RoomSize, NoofAvailableBed, RoomPricePerHead, Status) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(insertQuery);
            pstmt.setInt(1, roomID);
            pstmt.setString(2, bedType);
            pstmt.setInt(3, roomSize);
            pstmt.setInt(4, noOfOccupants);
            pstmt.setDouble(5, roomPrice);
            pstmt.setString(6, status);
            int rowsInserted = pstmt.executeUpdate();

            if (rowsInserted > 0) {
                javax.swing.JOptionPane.showMessageDialog(null, "Room added successfully!");
                
                loadData();
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Failed to add room.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            pstmt.close();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid input! Please enter the correct data types.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_bttnAddRoomsActionPerformed

    private void bttnDeleteRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeleteRoomsActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a room to delete.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    int roomID = (int) jTable1.getValueAt(selectedRow, 0);
    String bedType = (String) jTable1.getValueAt(selectedRow, 1);

    
    javax.swing.JTextField reasonField = new javax.swing.JTextField();
    Object[] message = {
        "Room ID: " + roomID + "\nBed Type: " + bedType + "\n\nPlease enter the reason for deletion:", reasonField
    };

    int option = javax.swing.JOptionPane.showConfirmDialog(this, message, "Delete Room", javax.swing.JOptionPane.OK_CANCEL_OPTION);
    if (option == javax.swing.JOptionPane.OK_OPTION) {
        String reason = reasonField.getText().trim();
        if (reason.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Reason cannot be empty. Please provide a valid reason.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "The room will be deleted because: " + reason + "\nAre you sure you want to proceed?",
            "Confirm Deletion",
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                
                String deleteQuery = "DELETE FROM rooms WHERE RoomID = ?";
                PreparedStatement pstmt = conn.prepareStatement(deleteQuery);
                pstmt.setInt(1, roomID);
                int rowsDeleted = pstmt.executeUpdate();

                if (rowsDeleted > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Room deleted successfully!");
                    
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.removeRow(selectedRow);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete the room. It may not exist in the database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                pstmt.close();
            } catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_bttnDeleteRoomsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Available_Apartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Available_Apartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Available_Apartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Available_Apartments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Available_Apartments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAddRooms;
    private javax.swing.JButton bttnDeleteRooms;
    private javax.swing.JButton bttnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
